#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require 'yaml'
require 'erb'

ENV['RAILS_ENV'] ||= ARGV[1]

raise Exception.new("You must specify a rails environment") if ENV['RAILS_ENV'].nil? || ENV['RAILS_ENV'] == ''

class Hash
  def with_symbols!
    self.keys.each{|key| self[key.to_s.to_sym] = self[key] }; self
  end
end

options = YAML.load(
  ERB.new(
  IO.read(
  File.dirname(__FILE__) + "/../../config/daemons.yml"
  )).result).with_symbols!
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run File.dirname(__FILE__) + '/flickr_daemon.rb', options